### PR TITLE
Update new-production-install.md

### PR DESCRIPTION
**Pull request by adamancini**
add Registry, Security & Access, and Storage headers, and move the "additional tasks" into an examples comment

### CODE REVIEW

**Comment by dexhorthy** [comment]
@adamancini i didn't document this anywhere but I think this change needs to happen over here now (we no longer pull from starter repo, all templates live in ce-automation and will get pushed here instead).

https://github.com/replicatedhq/ce-automation/tree/main/tf-github-boards/boards-module/.github/ISSUE_TEMPLATE

**Comment by adamancini** [comment]
@dexhorthy ok that makes sense and I was going to suggest we do something like that so we didn't have to depend on this cross-repo lookup

**Comment by adamancini** [comment]
I'll make this PR in the new spot

**Comment by dexhorthy** [comment]
👍 sounds good -- wanna close this one?

**Pull request closed without merging**
