### PR TITLE
remove contour from default kurl spec

### PR DESCRIPTION
**Pull request by adamancini**

### CODE REVIEW

**Comment by tdensmore** [comment]
LGTM

**Comment by jdewinne** [comment]
@tdensmore @adamancini We sure about doing this?
The repo also contains an Ingress resource
https://github.com/replicatedhq/replicated-starter-kots/blob/main/manifests/example-ingress.yaml

**Comment by adamancini** [comment]
@jdewinne we could add an option to deploy an Ingress Controller with a checkbox on the Config screen as an optional inclusion

**Comment by jdewinne** [comment]
Sure, or just remove the Ingress manifest and add something different in the Config.
I haven't tested it, but I think the current `main` branch isn't going to deploy now?

**Comment by adamancini** [comment]
wouldn't it deploy but the Ingress would just be a no-op?

**Pull request merged**
